# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build contest-framework`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t contest-framework`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system contest-framework && \
  adduser --system -G contest-framework contest-framework

COPY dist/contest-framework contest-framework/
RUN chown -R contest-framework:contest-framework .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix contest-framework --omit=dev -f install

CMD [ "node", "contest-framework" ]
